name: Python testing

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Create virtual environment
      run: |
        python3 -m venv env
        source env/bin/activate
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Testing
      run: |
        pytest
