name: Python testing

on: [push, pull_request]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    
    - name: Create virtual environment
      run: |
        python3 -m venv env
        source env/bin/activate
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: .
    
    - name: Testing
      run: |
        pytest
      working-directory: .
